export const isDev = process.env.NODE_ENV === 'development'
export const isProd = process.env.NODE_ENV === 'production'

const env = {
  NEXT_PUBLIC_CHAT_TEXT_MESSAGE_MAX_SIZE: 1024 * 1024,
  NEXT_PUBLIC_CHAT_ATTACHMENT_MAX_SIZE: 25 * 1024 * 1024,
  NEXT_PUBLIC_CHAT_ATTACHMENT_FILENAME_MAX_SIZE: 10 * 1024,
  NEXT_PUBLIC_MARKET_LISTING_ATTACHMENT_LIMIT: 10,
  NEXT_PUBLIC_MARKET_LISTING_ATTACHMENT_SIZE_LIMIT: 5 * 1024 * 1024,
  NEXT_PUBLIC_MARKET_LISTING_TITLE_MAX_LENGTH: 200,
  NEXT_PUBLIC_MARKET_LISTING_DESCRIPTION_MAX_LENGTH: 1200,
}

export default env
